name: Build from no-master

on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches:
      - '*'

  
jobs:
  build-test-docker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build app
      run: docker build . -t sml-app